### ISSUE TITLE
TODO for PRs

### ISSUE THREAD

**Issue by evguu** [daveschumaker/artbot-for-stable-diffusion#98]
I'll try to complete what I can
- [x] Dimension swap icon is misleading
- [x] Aspect ratio button looks unconventional
- [x] 'Copy image to clipboard' button requires scrolling on mobile

**Comment by evguu** [comment]
Solved in #101
